### ISSUE TITLE
ClientOnly Not Protecting Component

### ISSUE THREAD

**Issue by CSFlorin** [sergiodxa/remix-utils#144]
### Describe the bug

Using https://github.com/rmariuzzo/react-new-window which calls `window.document` inside ClientOnly, like this:

```
<ClientOnly fallback={<div />}>
	{() => (
		<NewWindow>
			<h1>Hi 👋</h1>
		</NewWindow>
	)}
</ClientOnly>
```

gives the following error:

```
TypeError: Cannot read properties of null (reading 'document')
    at u2.value (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/routes/index-GKHCLL4X.js:139:60)
    at u2.value (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/routes/index-GKHCLL4X.js:124:50)
    at commitLifeCycles (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/_shared/chunk-FBU2B6A6.js:15154:30)
    at commitLayoutEffects (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/_shared/chunk-FBU2B6A6.js:16903:15)
    at HTMLUnknownElement.callCallback2 (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/_shared/chunk-FBU2B6A6.js:3793:22)
    at Object.invokeGuardedCallbackDev (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/_shared/chunk-FBU2B6A6.js:3818:24)
    at invokeGuardedCallback (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/_shared/chunk-FBU2B6A6.js:3852:39)
    at commitRootImpl (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/_shared/chunk-FBU2B6A6.js:16725:17)
    at unstable_runWithPriority (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/_shared/chunk-FBU2B6A6.js:344:20)
    at runWithPriority$1 (https://node47yqlu-arbv--3000.local-credentialless.webcontainer.io/build/_shared/chunk-FBU2B6A6.js:8596:18)
```

A full repro is available at https://stackblitz.com/edit/node-47yqlu?file=app/routes/index.tsx You must click the button at the top right of StackBlitz to "Open in New Tab" to avoid the cross-origin frame error:
<img width="141" alt="image" src="https://user-images.githubusercontent.com/9855031/211265841-63215f18-28be-4ade-8a85-30b9d71bc62c.png">

### Your Example Website or App

https://stackblitz.com/edit/node-47yqlu?file=app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. Install remix-utils and react-new-window
2. Use react-new-window's `NewWindow` inside remix-utils' `ClientOnly`

### Expected behavior

I expect a new window to open. It does seem to work when you start on another page and then go to that page. But when the page that has this code is the first render, it fails.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 108.0.5359.124

**Comment by sergiodxa** [comment]
Create a `new-window.client.ts` file somewhere inside `app` and outside `app/routes` and add

```ts
import NewWindow from 'react-new-window';
export { NewWindow };
```

Then import NewWindow from there, this will tell Remix to only include that `new-window.client.ts` file on the client-side bundle, on the server the exported NewWindow component will be undefined, with ClientOnly you can prevent trying to render that undefined on the server and delay it to the browser.

If it still blows up then there's something bad in the package.

**Comment by CSFlorin** [comment]
ahhh that makes sense! they are probably accessing window outside the component. thanks!
